### ISSUE TITLE
plistlib.py doesn't work in 2.7

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufoLib#35]
```
Traceback (most recent call last):
  File "/.../ufoLib/Lib/ufoLib/plistlib.py", line 53, in <module>
    from plistlib import readPlist, writePlist, readPlistFromString, writePlistToString
  File "/.../ufoLib/Lib/ufoLib/plistlib.py", line 53, in <module>
    from plistlib import readPlist, writePlist, readPlistFromString, writePlistToString
ImportError: cannot import name readPlist
```

It seems that even with the `absolute_import` statement it is still trying to pull the ufoLib version of plistlib. If I chance the contents of plistlib.py to this:

```python
from __future__ import absolute_import
import plistlib
print plistlib.__file__
```

I get:

```
/.../ufoLib/Lib/ufoLib/plistlib.py
/.../ufoLib/Lib/ufoLib/plistlib.py
```

I'm using stock Python in OS 10.10.

```
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
```

Any suggestions?

**Comment by typesupply** [comment]
cc @adrientetar

**Comment by anthrotype** [comment]
I can't reproduce the issue you are referring to.
Try to create a fresh virtualenv and install ufoLib inside that and see if the issue still shows up.
I might be that you have some `.pth` file that's messing up your PYTHONPATH.

**Comment by typesupply** [comment]
I think it only happens when a script is executed via Sublime Text. The code seems fine. I'll close this and add a note here if I can figure out how to fix it in the editor.
